# pipeline.yml
name: My pipeline
description: A simple pipeline
workers:

  - name: fetch_mbedtls
    package: Git Scrapper
    target: compile_mbedtls
    args:
      repositories:
        - name: libc
          url: https://github.com/Mbed-TLS/mbedtls
          submodule: true
          branches:
            - mbedtls-4.0.0
            - mbedtls-3.0.0
            - mbedtls-2.0.0

  - name: compile_mbedtls
    package: Cmake Compiler
    target: analyzer
    foreach:
      - compiler_variants:
          arm-O0:
            cc: arm-linux-gnueabi-gcc
            cflags: -O0

  - name: analyzer
    package: Ghidra Analyzer
    args:
      bsim:
        urls:
          - postgresql://user@bsim_postgres:5432/bsim
        min_instructions: 10
        max_instructions: 0
