site_name: SightHouse Documentation 
site_url: http://localhost:8000/sighthouse/ 
site_author: Fenrisfulsur & Madsquirrels 
repo_url: "https://github.com/quarkslab/sighthouse"
repo_name: "quarkslab/sighthouse"

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default 
      primary: teal
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode

  features:
    - navigation.indexes
    - navigation.top

# Download external ressources to enhance privacy
plugins:
  - privacy
  - search
  - inline-svg
  # Uncomment this to have PDF generation
  # - to-pdf:
  #     cover_title: SightHouse Documentation 
  #     cover_subtitle: A tool designed to assist reverse engineers 
  #     download_link: header
  - mkdocstrings:
      handlers:
        python:
          options:
            backlinks: tree
            docstring_options:
              per_style_options:
                google:
                  ignore_init_summary: true
            filters:
              - "!^__"
              - "!^_"
            docstring_style: auto
            docstring_section_style: list
            extensions:
            - griffe_inherited_docstrings
            - unpack_typeddict
            heading_level: 2
            inherited_members: true
            merge_init_into_class: true
            parameter_headings: true
            separate_signature: true
            show_bases: true
            show_inheritance_diagram: false 
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true

hooks:
  - package_hook.py
  - frontend_hook.py

extra_css:
  - assets/css/override-material.css

# Required for pretty images
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.blocks.caption
  - pymdownx.superfences
  - pymdownx.details

nav:
  - Home: index.md
  - SRE Clients:
    - Installation: clients/installation.md
    - Quickstart: clients/quickstart.md 
  - Frontend:
    - Installation: frontend/installation.md
    - Quickstart: frontend/quickstart.md 
  - Signature Pipeline:
    - Installation: signature-pipeline/installation.md
    - Quickstart: signature-pipeline/quickstart.md 
    - How It Works: signature-pipeline/how.md
    - Custom modules: signature-pipeline/dev.md
  - API Reference:
    - Index: api-reference/index.md
    - Core: api-reference/core.md
    - Client: api-reference/client.md
    - Frontend: api-reference/frontend.md
    - Pipeline: api-reference/pipeline.md
